#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TCM_ONCELL) +=syna_tcm_oncell/
#obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += synaptics_touch_panel_remote.o
#obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += synaptics_common.o

obj-y += synaptics_touch_panel_remote.o
obj-y += synaptics_common.o
#endif
