#/************************************************************************************
#** File: - Makefile
#** Copyright (C), 2008-2020, OPLUS Mobile Comm Corp., Ltd
#**
#** Description:
#**      1. Add for routerboost
#**
#** Version: 1.0
#** Date :   2021-04-09
#** TAG  :   OPLUS_FEATURE_WIFI_ROUTERBOOST
#**
#** ---------------------Revision History: ---------------------
#**  <author>                      <data>     <version >   <desc>
#** ---------------------------------------------------------------
#**
#************************************************************************************/

#
# Makefile for the netfilter modules on top of IPv4.
#
obj-$(CONFIG_OPLUS_FEATURE_WIFI_ROUTERBOOST) += oplus_connectivity_routerboost.o
oplus_connectivity_routerboost-objs := oplus_routerboost.o oplus_routerboost_game_monitor.o
