subdir-ccflags-y += -Werror
subdir-ccflags-y += -Wno-unused-variable

obj-$(ONEPLUS_STEP_MOTOR)	+= camera_motor_ic/
obj-$(ONEPLUS_STEP_MOTOR)	+= digital_hall_ic/

obj-$(ONEPLUS_STEP_MOTOR)	+= oneplus_motor.o
obj-$(ONEPLUS_STEP_MOTOR)	+= oneplus_motor_notifier.o
