# oem device driver for charge
obj-$(CONFIG_FG_BQ27541)		+= bq27541_fuelgauger.o
obj-$(CONFIG_ONEPLUS_FASTCHG)	+= oneplus_fastchg.o
obj-$(CONFIG_CP_DA9313)			+= op_da9313.o
obj-$(CONFIG_CHGIC_MP2762)		+= op_mp2650.o

