# oem device driver for charge
#obj-$(CONFIG_FG_BQ27541)	+= bq27541_fuelgauger.o
#obj-$(CONFIG_ONEPLUS_FASTCHG)	+= oneplus_fastchg.o op_dash_adapter.o
obj-y	+= bq27541_fuelgauger.o
obj-y	+= oneplus_fastchg.o

